services:
  mongo:
    image: mongo:7
<<<<<<< HEAD
    container_name: proyecto-semana-08-mongo
    ports:
      - "27017:27017"
    volumes:
      - proyecto-mongo-data:/data/db

volumes:
  proyecto-mongo-data:
=======
    container_name: vendmax_mongo
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: vendmax
      MONGO_INITDB_ROOT_PASSWORD: vendmax123
      MONGO_INITDB_DATABASE: vendmax_dev
    ports:
      - "27017:27017"
    volumes:
      - vendmax_mongo_data:/data/db

volumes:
  vendmax_mongo_data:
>>>>>>> 3339a8116a24bcc88df890a9c06c2e1a74cb61b8
